name: Auto approve

on:
  workflow_run:
    workflows: ["PR Tests"]
    types:
      - completed

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0].user.login == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
