name: Publish to PyPI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install

    - name: Install the project dependencies
      run: uv sync --all-groups

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files

    - name: Run tests
      run: uv run pytest

    - name: Build package
      run: uv build --no-sources

    - name: Publish to PyPI
      run: uv publish
