name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Type Checking, Security Scanning, and Code Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - uses: actions/cache@v3
      name: Cache uv dependencies
      with:
        path: |
          .uv/cache
          .venv
        key: uv-${{ hashFiles('uv.lock') }}

    - name: Install the project dependencies
      run: uv sync --all-groups

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files

  test:
    name: Test on Python 3.12
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - uses: actions/cache@v3
      name: Cache uv dependencies
      with:
        path: |
          .uv/cache
          .venv
        key: uv-${{ hashFiles('uv.lock') }}

    - name: Install the project dependencies
      run: uv sync

    - name: Run tests with coverage
      run: uv run pytest --cov=src --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

  test-python-313:
    name: Test on Python 3.13
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - uses: actions/cache@v3
      name: Cache uv dependencies
      with:
        path: |
          .uv/cache
          .venv
        key: uv-${{ hashFiles('uv.lock') }}

    - name: Install the project dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest
