name: Publish to PyPI

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  UV_CACHE_DIR: ${{ github.workspace }}/.uv_cache

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-groups

    - name: Run pre-commit hooks
      run: uv run pre-commit run --all-files

    - name: Run tests
      run: uv run pytest

    - name: Build package
      run: uv build --no-sources

    - name: Publish to PyPI
      run: uv publish
